version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  localstack:
    container_name: "${complaint-system-localstack}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4572:4572"
      - "8055:8080"
    environment:
      - SERVICES=sqs
      - LAMBDA_EXECUTOR=docker_reuse
      - DEFAULT_REGION=us-east-2
      - HOSTNAME=localhost
      - LAMBDA_DOCKER_NETWORK=localstack-tutorial
    volumes:
      - /var/log/aws_localstack:/var/log/

